repos:
  - repo: local
    hooks:
      - id: security-guard-pre-commit-pre-push
        name: security-guard
        entry: bash .github/scripts/security-guard.sh
        language: system
        pass_filenames: true
        stages: [pre-commit, pre-push]
